/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreatePerformanceArgs } from "./CreatePerformanceArgs";
import { UpdatePerformanceArgs } from "./UpdatePerformanceArgs";
import { DeletePerformanceArgs } from "./DeletePerformanceArgs";
import { PerformanceFindManyArgs } from "./PerformanceFindManyArgs";
import { PerformanceFindUniqueArgs } from "./PerformanceFindUniqueArgs";
import { Performance } from "./Performance";
import { Player } from "../../player/base/Player";
import { PerformanceService } from "../performance.service";

@graphql.Resolver(() => Performance)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PerformanceResolverBase {
  constructor(
    protected readonly service: PerformanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "any",
  })
  async _performancesMeta(
    @graphql.Args() args: PerformanceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Performance])
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "any",
  })
  async performances(
    @graphql.Args() args: PerformanceFindManyArgs
  ): Promise<Performance[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Performance, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "own",
  })
  async performance(
    @graphql.Args() args: PerformanceFindUniqueArgs
  ): Promise<Performance | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Performance)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "create",
    possession: "any",
  })
  async createPerformance(
    @graphql.Args() args: CreatePerformanceArgs
  ): Promise<Performance> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        player: args.data.player
          ? {
              connect: args.data.player,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Performance)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "update",
    possession: "any",
  })
  async updatePerformance(
    @graphql.Args() args: UpdatePerformanceArgs
  ): Promise<Performance | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          player: args.data.player
            ? {
                connect: args.data.player,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Performance)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "delete",
    possession: "any",
  })
  async deletePerformance(
    @graphql.Args() args: DeletePerformanceArgs
  ): Promise<Performance | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Player, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Player",
    action: "read",
    possession: "any",
  })
  async player(@graphql.Parent() parent: Performance): Promise<Player | null> {
    const result = await this.service.getPlayer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
