/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PerformanceService } from "../performance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PerformanceCreateInput } from "./PerformanceCreateInput";
import { PerformanceWhereInput } from "./PerformanceWhereInput";
import { PerformanceWhereUniqueInput } from "./PerformanceWhereUniqueInput";
import { PerformanceFindManyArgs } from "./PerformanceFindManyArgs";
import { PerformanceUpdateInput } from "./PerformanceUpdateInput";
import { Performance } from "./Performance";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PerformanceControllerBase {
  constructor(
    protected readonly service: PerformanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Performance })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PerformanceCreateInput
  ): Promise<Performance> {
    return await this.service.create({
      data: {
        ...data,

        player: data.player
          ? {
              connect: data.player,
            }
          : undefined,
      },
      select: {
        assists: true,
        createdAt: true,
        dayOfTheLeague: true,
        goals: true,
        id: true,
        penaltiesFailed: true,

        player: {
          select: {
            id: true,
          },
        },

        redCards: true,
        updatedAt: true,
        vote: true,
        yellowCards: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Performance] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PerformanceFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Performance[]> {
    const args = plainToClass(PerformanceFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        assists: true,
        createdAt: true,
        dayOfTheLeague: true,
        goals: true,
        id: true,
        penaltiesFailed: true,

        player: {
          select: {
            id: true,
          },
        },

        redCards: true,
        updatedAt: true,
        vote: true,
        yellowCards: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Performance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PerformanceWhereUniqueInput
  ): Promise<Performance | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        assists: true,
        createdAt: true,
        dayOfTheLeague: true,
        goals: true,
        id: true,
        penaltiesFailed: true,

        player: {
          select: {
            id: true,
          },
        },

        redCards: true,
        updatedAt: true,
        vote: true,
        yellowCards: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Performance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PerformanceWhereUniqueInput,
    @common.Body() data: PerformanceUpdateInput
  ): Promise<Performance | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          player: data.player
            ? {
                connect: data.player,
              }
            : undefined,
        },
        select: {
          assists: true,
          createdAt: true,
          dayOfTheLeague: true,
          goals: true,
          id: true,
          penaltiesFailed: true,

          player: {
            select: {
              id: true,
            },
          },

          redCards: true,
          updatedAt: true,
          vote: true,
          yellowCards: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Performance",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Performance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PerformanceWhereUniqueInput
  ): Promise<Performance | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          assists: true,
          createdAt: true,
          dayOfTheLeague: true,
          goals: true,
          id: true,
          penaltiesFailed: true,

          player: {
            select: {
              id: true,
            },
          },

          redCards: true,
          updatedAt: true,
          vote: true,
          yellowCards: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
